version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: NikhilMySQL@987
      MYSQL_DATABASE: scraping_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=scraping_db
      - DB_USER=root
      - DB_PASSWORD=NikhilMySQL@987
    depends_on:
      - mysql

volumes:
  mysql_data:
